name: Java CI
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Automation-Test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests
        run: mvn test -P ci-qc -DBS_ACCESS_KEY=${{ secrets.BS_ACCESS_KEY }} -DBS_USERNAME=${{ secrets.BS_USERNAME }} -DBS_APP=${{ secrets.BS_APP }} -pl onboarding-mobile,onboarding-web


